# IPAddressPool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: origo-pool # can be changed to anything you like
  namespace: metallb-system
spec:
  addresses:
  # For each single ip-address you want to add to the pool,
  # uncomment a copy of the below line and replace "1.2.3.4" 
  # with the ip-address.
  # - 1.2.3.4/32
  # For each range of ip-address you want to add to the pool,
  # uncomment a copy of the below line and replace "5.6.7.8" 
  # with the start of the ip-range and "5.6.7.18" with the 
  # end of the ip-range.
  # - 5.6.7.8-5.6.7.18
